### ISSUE TITLE
Create sitemapindex and separate sitemap files for larger sites

### ISSUE THREAD

**Issue by coret** [ManOnDaMoon/omeka-s-module-Sitemaps#1]
The collections in our Omeka S instance are growing, so the limits of the current one sitemap (per site) will become an issue.

https://github.com/ManOnDaMoon/omeka-s-module-Sitemaps/blob/c216ff16efe7a4fba81898d59eecfadd408d93eb/src/Controller/Site/SitemapsController.php#L20

Google [says](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap) the limit is 50000 entries:
> Break up large sitemaps into smaller sitemaps: a sitemap can contain up to 50,000 URLs and must not exceed 50MB uncompressed. Use a [sitemap index file](https://developers.google.com/search/docs/crawling-indexing/sitemaps/large-sitemaps) to list all the individual sitemaps and submit this single file to Google rather than submitting individual sitemaps.

**Comment by ManOnDaMoon** [comment]
Thanks for the suggestion. I'll have a look at how to implement a pagination and an sitemap index, maybe making it a configurable option too.

The file size issue is a bit more challenging though, as these sitemaps are not actual files on the server, but dynamically generated xml content.

**Comment by coret** [comment]
I think the logic should be, that if the number of items in the sitemap is above the configured limit (default:50000), then a request to `https://{domain}/{site-slug}/sitemap.xml` should give a response like:

```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<sitemap>
		<loc>https://{domain}/{site-slug}/sitemap.xml?part=1</loc>
		<lastmod>2023-02-11T15:23:50+00:00</lastmod>
	</sitemap>
	<sitemap>
		<loc>https://{domain}/{site-slug}/sitemap.xml?part=2</loc>
		<lastmod>2023-02-08T23:17:03+00:00</lastmod>
	</sitemap>
         ....
</sitemapindex>
```

It's for the spiders then, to harvest each sitemap part. In this setup it's no problem that the XML files are dynamically generated upon request (although some caching never hurts).

**Comment by ManOnDaMoon** [comment]
I've pushed a first implementation of this feature to the [sitemap-index](https://github.com/ManOnDaMoon/omeka-s-module-Sitemaps/tree/sitemap-index) branch.

The logic is similar except this is an opt-in feature: you have to enable the sitemap index on each site. This is to keep the current behavior for sites that already make use of the module.

The _Enable sitemap index_ setting is located under site settings. It activates the .../sitemapindex.xml file URL. This file contains at least 3 sitemaps urls:
* pages URLs
* item sets URLs
* items URLs

Here is a sample generated sitemap index XML file:
```xml
<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
    	<loc>http://localhost:8888/s/fr/sitemap-1.xml</loc>
    	<lastmod>2020-11-19</lastmod>
    </sitemap>
    <sitemap>
    	<loc>http://localhost:8888/s/fr/sitemap-2.xml</loc>
    	<lastmod>2020-11-19</lastmod>
    </sitemap>
    <sitemap>
    	<loc>http://localhost:8888/s/fr/sitemap-3.xml</loc>
    	<lastmod>2022-12-21</lastmod>
    </sitemap>
</sitemapindex>
```

There is also a _Sitemap max entry count_ setting that lets you select your own limit. The Google limit is technical, generally you'd want crawlers to have quickly accessible files and avoid timeouts, thus limiting way below the 50k entries. 500 or 1k are the usually advised numbers here.

Depending on settings, the sitemap.xml file may redirect to sitemapindex.xml and vice-versa.

Let me know if you have the ability to test it against a large instance and maybe compare with existing sitemaps?

**Comment by coret** [comment]
Nice!!

I've installed the sitemap-index branch of the Sitemap module and all seems well. I've enabled the sitemap index on 3 sites, with a max entry of 1000. I'll keep a close watch on [Google Search Console](https://search.google.com/) to see if Google also likes what it sees.

One question though, about for example https://www.goudatijdmachine.nl/data/indexen/sitemapindex.xml:

```
<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
    	<loc>https://www.goudatijdmachine.nl/data/indexen/sitemap-1.xml</loc>
    	<lastmod>2023-02-05</lastmod>
    </sitemap>
    <sitemap>
    	<loc>https://www.goudatijdmachine.nl/data/indexen/sitemap-2.xml</loc>
    	<lastmod>2022-11-21</lastmod>
    </sitemap>
    <sitemap>
    	<loc>https://www.goudatijdmachine.nl/data/indexen/sitemap-3.xml</loc>
    	<lastmod>2023-01-09</lastmod>
    </sitemap>
....
    <sitemap>
    	<loc>https://www.goudatijdmachine.nl/data/indexen/sitemap-40.xml</loc>
    	<lastmod>2022-02-27</lastmod>
    </sitemap>
</sitemapindex>
```

How is this lastmod date calculated? Is this the most recent lastmod of pages within the specific sitemap?

**Comment by ManOnDaMoon** [comment]
> Is this the most recent lastmod of pages within the specific sitemap?

That is correct. The `lastmod` tag is optional but I included it since I had to chronologically sort the entries in the first place, meaning the most recent entries will come up at the beginning of each sitemap. That way the crawlers will have a hint that somewhere in between those pages (e.g. [the begining of the items' sitemaps section](https://www.goudatijdmachine.nl/data/indexen/sitemap-3.xml)) there has been an update to parse for them.

**Comment by coret** [comment]
I had configured the sitemapindex on 3 of 4 websites, which are working great (I see them popup in Google Search Console too).

One of my sites has no siteindex and it seems this "old" sitemap no throws an error:

```
Laminas\View\Exception\RuntimeException: Laminas\View\Renderer\PhpRenderer::render: Unable to render template "sitemaps/site/sitemaps/sitemap"; resolver could not resolve to a file in **/omeka-s-4.0.0/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php:511
Stack trace:
#0 **/omeka-s-4.0.0/vendor/laminas/laminas-view/src/View.php(194): Laminas\View\Renderer\PhpRenderer->render()
#1 **/omeka-s-4.0.0/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render()
#2 **/omeka-s-4.0.0/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren()
#3 **/omeka-s-4.0.0/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render()
#4 **/omeka-s-4.0.0/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render()
#5 **/omeka-s-4.0.0/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners()
#6 **/omeka-s-4.0.0/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas\EventManager\EventManager->triggerEvent()
#7 **/omeka-s-4.0.0/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc\Application->completeRequest()
#8 **/omeka-s-4.0.0/index.php(21): Laminas\Mvc\Application->run()
#9 {main}
```

**Comment by ManOnDaMoon** [comment]
Is your site located on the same Omeka-S install as the other working sites?
The error message itself means there is a file that should be located in the module directory that is not found.
It does not refer to any of this modules' code, thus making me wonder if the module is correctly installed or even present.

If the module is indeed present, could you share a capture of the site settings so that I can try and reproduce the error?

EDIT: I've been able to reproduce the same error by deleting or moving the `sitemap.phtml` file located in `omeka-s/modules/Sitemaps/view/site/`. Could you check if yours exists?

**Comment by coret** [comment]
> Is your site located on the same Omeka-S install as the other working sites?

Yes, it's one installation with 4 sites.

> The error message itself means there is a file that should be located in the module directory that is not found.
> It does not refer to any of this modules' code, thus making me wonder if the module is correctly installed or even present.

The strange thing is, that https://www.goudatijdmachine.nl/data/indexen/sitemap-1.xml works (and this of course uses the same sitemap.phtml file, which show it's present), but https://www.goudatijdmachine.nl/data/datasets/sitemap.xml keeps throwing the 'Unable to render template "sitemaps/site/sitemaps/sitemap"' error.

Tommorow, I'll install the module from the main branch, to check if all 4 sitemaps are ok.

**Comment by ManOnDaMoon** [comment]
Thanks for the additional info, I've been able to pinpoint the issue and d0d2c5a15f5da7680a83ed0852e2a02718baf5de should fix this behavior.

**Comment by coret** [comment]
Yes, I've applied the fix and the issue is solved now (https://www.goudatijdmachine.nl/data/datasets/sitemap.xml with 'Enable sitemap index' off, now shows a sitemap)

**Comment by ManOnDaMoon** [comment]
Published in https://github.com/ManOnDaMoon/omeka-s-module-Sitemaps/releases/v1.1
