### ISSUE TITLE
Sitemaps wrapped in HTML

### ISSUE THREAD

**Issue by m8hu** [ManOnDaMoon/omeka-s-module-Sitemaps#3]
Having an issue getting the sitemaps to output as xml files. 

I'm working across a few staging copies as I develop and the issue is the same on all three. (one local, two on a dedicated cpanel server) The sitemap.xml is being output wrapped in: 

```
<!-- ?xml version="1.0" encoding="UTF-8"? -->
<html>
<head></head>
<body>
[[ sitemap as it should be from sitemap.phtml ]]
</body>
</html>
``` 

Any chance you've run into this before or know of potential conflicts with a theme that would force this kind of a wrapper? I'm on a modification of the Freedom theme.

**Comment by ManOnDaMoon** [comment]
I've installed the Freedom theme locally and I'm unable to reproduce the issue.

Are you sure you're looking at the XML file and not your browser's rendition of it? In the web inspector panel, you should look at the Source tab, and not the Elements tab. It's usually accessible using the Ctrl+U keyboard shortcut (or Option+Cmd+U on Apple devices).

**Comment by m8hu** [comment]
Apologies, that's accurate. My browser added the html. Re-running the urls with curl I'm getting pure XML as it should be. 

Meaning the real issue is somewhere, somehow, my content-type header is being re-written to ```text/html; charset=UTF-8``` not the ```application/xml``` that i need it to be. If I drop an xml file on the server I'm getting the correct header, just not from the module generated url.

**Comment by ManOnDaMoon** [comment]
You're right. I've added the correct Content Type header to the response in 2288660. Would you be able to try it out?

**Comment by m8hu** [comment]
Perfection. Getting a clean read on the doc this way. 

Much appreciated on the update.
